-- =====================================================================
--  Data contoh DUKCAPIL (opsional). Import SETELAH schema.sql.
--  Akun peserta demo: raka / andi / sinta / dewi — password: User@123
--  Seluruh soal dapat diubah / dihapus admin melalui menu Question Bank.
-- =====================================================================
SET NAMES utf8mb4;

INSERT INTO users (id, name, username, email, password, role, department, position, status) VALUES
(2, 'Raka Aprilio',   'raka',  'raka@example.com',  '$2y$10$CZ4t2UNNXTSJQ701XAd.nuMEf4mhL8lHNuk5gUMA41OxlYjzaQ1h2', 'user', 'Bidang Dafduk', 'Operator Pelayanan KTP-el', 'active'),
(3, 'Andi Saputra',   'andi',  'andi@example.com',  '$2y$10$CZ4t2UNNXTSJQ701XAd.nuMEf4mhL8lHNuk5gUMA41OxlYjzaQ1h2', 'user', 'Bidang Capil',  'Verifikator Akta',         'active'),
(4, 'Sinta Maharani', 'sinta', 'sinta@example.com', '$2y$10$CZ4t2UNNXTSJQ701XAd.nuMEf4mhL8lHNuk5gUMA41OxlYjzaQ1h2', 'user', 'Bidang PIAK',   'Pengelola Data SIAK',      'active'),
(5, 'Dewi Lestari',   'dewi',  'dewi@example.com',  '$2y$10$CZ4t2UNNXTSJQ701XAd.nuMEf4mhL8lHNuk5gUMA41OxlYjzaQ1h2', 'user', 'Bidang PDIP',   'Analis Inovasi Pelayanan', 'active');

UPDATE users SET department = 'Sekretariat', position = 'Administrator Sistem' WHERE id = 1;

INSERT INTO categories (id, name, description) VALUES
(1, 'Regulasi Adminduk', 'UU 23/2006 jo. UU 24/2013 dan peraturan pelaksana'),
(2, 'Pencatatan Sipil', 'Kelahiran, kematian, perkawinan, dan peristiwa penting lainnya'),
(3, 'Pendaftaran Penduduk', 'KK, KTP-el, KIA, pindah datang'),
(4, 'Digitalisasi & Data', 'SIAK, IKD, TTE, perlindungan data'),
(5, 'Pelayanan Publik & Etika', 'Standar pelayanan, integritas, anti pungli');

INSERT INTO questions (id, category_id, question, question_type, difficulty, points, explanation, created_by) VALUES
(1, 1, 'Dasar hukum utama penyelenggaraan Administrasi Kependudukan di Indonesia adalah...', 'multiple_choice', 'easy', 2, 'Administrasi Kependudukan diatur dalam UU 23/2006 yang telah diubah dengan UU 24/2013.', 1),
(2, 1, 'Nomor Induk Kependudukan (NIK) terdiri dari berapa digit?', 'multiple_choice', 'easy', 2, 'NIK terdiri dari 16 digit, bersifat unik, dan melekat seumur hidup.', 1),
(3, 1, 'Enam digit pertama pada NIK menunjukkan...', 'multiple_choice', 'medium', 2, 'Struktur NIK: 6 digit kode wilayah, 6 digit tanggal lahir, 4 digit nomor urut.', 1),
(4, 1, 'Pada NIK penduduk perempuan, angka tanggal lahir ditambah dengan...', 'multiple_choice', 'medium', 2, 'Untuk perempuan, digit tanggal lahir ditambah 40 (contoh: lahir tanggal 05 menjadi 45).', 1),
(5, 1, 'KTP-el berlaku seumur hidup.', 'true_false', 'easy', 1, 'Berdasarkan UU 24/2013, masa berlaku KTP-el adalah seumur hidup.', 1),
(6, 1, 'Penduduk WNI wajib memiliki KTP-el apabila...', 'multiple_choice', 'easy', 2, 'WNI dan orang asing dengan izin tinggal tetap wajib ber-KTP-el bila berumur 17 tahun atau telah kawin/pernah kawin.', 1),
(7, 1, 'Pengurusan dan penerbitan dokumen kependudukan dapat dipungut biaya sesuai peraturan daerah.', 'true_false', 'easy', 1, 'UU 24/2013 menegaskan pengurusan dan penerbitan dokumen kependudukan tidak dipungut biaya.', 1),
(8, 1, 'Peraturan Presiden yang mengatur Persyaratan dan Tata Cara Pendaftaran Penduduk dan Pencatatan Sipil adalah...', 'multiple_choice', 'medium', 2, 'Perpres 96/2018 mengatur persyaratan & tata cara pendaftaran penduduk dan pencatatan sipil. Perpres 95/2018 tentang SPBE, Perpres 39/2019 tentang Satu Data Indonesia.', 1),
(9, 1, 'Manakah yang termasuk Peristiwa Penting? (pilih semua yang benar)', 'multiple_answer', 'hard', 3, 'Pindah datang adalah Peristiwa Kependudukan, sedangkan kelahiran, kematian, dan perkawinan adalah Peristiwa Penting.', 1),
(10, 1, 'Manakah yang termasuk Dokumen Kependudukan? (pilih semua yang benar)', 'multiple_answer', 'medium', 3, 'Paspor merupakan dokumen keimigrasian, bukan dokumen kependudukan.', 1),
(11, 2, 'Kelahiran wajib dilaporkan kepada instansi pelaksana paling lambat ... sejak kelahiran.', 'multiple_choice', 'easy', 2, 'Setiap kelahiran wajib dilaporkan paling lambat 60 hari sejak kelahiran (UU 24/2013).', 1),
(12, 2, 'Kematian wajib dilaporkan paling lambat ... sejak tanggal kematian.', 'multiple_choice', 'easy', 2, 'Kematian wajib dilaporkan paling lambat 30 hari sejak tanggal kematian.', 1),
(13, 2, 'Perkawinan yang sah wajib dilaporkan kepada instansi pelaksana paling lambat ... sejak tanggal perkawinan.', 'multiple_choice', 'medium', 2, 'Perkawinan wajib dilaporkan paling lambat 60 hari sejak tanggal perkawinan.', 1),
(14, 2, 'Pencatatan perkawinan bagi penduduk yang beragama Islam dilakukan oleh...', 'multiple_choice', 'medium', 2, 'Pencatatan perkawinan penduduk beragama Islam dilakukan KUA Kecamatan; datanya digunakan Dukcapil untuk pemutakhiran.', 1),
(15, 2, 'Akta Kelahiran diterbitkan oleh Dinas Kependudukan dan Pencatatan Sipil Kabupaten/Kota.', 'true_false', 'easy', 1, NULL, 1),
(16, 2, 'Dokumen yang diterbitkan sebagai bukti pencatatan peristiwa kematian disebut...', 'short_answer', 'medium', 2, 'Akta Kematian diterbitkan oleh Dinas Dukcapil berdasarkan laporan kematian.', 1),
(17, 3, 'Dokumen yang diterbitkan bagi penduduk yang pindah domisili ke kabupaten/kota lain adalah...', 'multiple_choice', 'medium', 2, NULL, 1),
(18, 3, 'Kartu Identitas Anak (KIA) diberikan kepada...', 'multiple_choice', 'easy', 2, 'KIA merupakan identitas resmi bagi anak berusia kurang dari 17 tahun dan belum kawin.', 1),
(19, 3, 'Kartu Keluarga wajib diperbarui apabila terjadi perubahan susunan anggota keluarga, misalnya karena kelahiran.', 'true_false', 'easy', 1, NULL, 1),
(20, 3, 'Penduduk yang KTP-el nya rusak wajib melakukan perekaman biometrik ulang dalam semua kasus.', 'true_false', 'medium', 1, 'Jika data biometrik sudah terekam di database, cukup cetak ulang tanpa perekaman ulang.', 1),
(21, 4, 'Kepanjangan dari SIAK adalah...', 'short_answer', 'medium', 2, 'SIAK adalah sistem informasi yang digunakan untuk pengelolaan data administrasi kependudukan.', 1),
(22, 4, 'IKD dalam layanan Dukcapil merupakan singkatan dari...', 'multiple_choice', 'easy', 2, 'IKD adalah identitas kependudukan dalam bentuk digital melalui aplikasi di ponsel.', 1),
(23, 4, 'Dokumen kependudukan seperti KK dan akta pencatatan sipil dapat dicetak pada kertas HVS dengan Tanda Tangan Elektronik (TTE) dan QR Code.', 'true_false', 'medium', 1, 'Penerapan TTE memungkinkan dokumen dicetak mandiri pada kertas HVS dan diverifikasi melalui QR Code.', 1),
(24, 4, 'Instansi pusat yang membina penyelenggaraan administrasi kependudukan adalah...', 'multiple_choice', 'easy', 2, NULL, 1),
(25, 4, 'Manakah yang termasuk Data Pribadi Penduduk yang wajib dilindungi menurut UU 24/2013? (pilih semua yang benar)', 'multiple_answer', 'hard', 3, 'Data pribadi yang dilindungi antara lain keterangan cacat fisik/mental, sidik jari, iris mata, tanda tangan, dan elemen data yang merupakan aib seseorang.', 1),
(26, 5, 'Seorang petugas meminta "uang terima kasih" agar KTP-el pemohon cepat selesai. Tindakan ini termasuk...', 'multiple_choice', 'easy', 2, 'Layanan dokumen kependudukan gratis; meminta imbalan adalah pungli dan melanggar hukum.', 1),
(27, 5, 'Undang-undang yang mengatur tentang Pelayanan Publik adalah...', 'multiple_choice', 'medium', 2, 'UU 25/2009 tentang Pelayanan Publik. UU 23/2014 tentang Pemerintahan Daerah, UU 14/2008 tentang KIP, UU 30/2014 tentang Administrasi Pemerintahan.', 1),
(28, 5, 'Petugas boleh memberikan data kependudukan seseorang kepada pihak lain tanpa hak akses yang sah, asalkan diminta oleh kerabatnya.', 'true_false', 'easy', 1, 'Data kependudukan hanya dapat diakses oleh pihak yang memiliki hak akses sesuai ketentuan.', 1),
(29, 5, 'Sikap yang paling tepat ketika menghadapi pemohon yang marah karena antrean panjang adalah...', 'multiple_choice', 'medium', 2, 'Pelayanan prima menuntut empati, komunikasi yang jelas, dan keadilan antrean.', 1),
(30, 3, 'Jelaskan langkah-langkah pelayanan bagi penduduk yang melaporkan KTP-el miliknya hilang.', 'essay', 'hard', 5, 'Poin penilaian: verifikasi identitas/NIK, persyaratan sesuai Perpres 96/2018 (mis. surat keterangan kehilangan), cek data biometrik di database, cetak ulang tanpa perekaman bila data tersedia, tidak dipungut biaya, informasikan waktu penyelesaian.', 1),
(31, 5, 'Sebutkan dan jelaskan minimal tiga upaya inovasi untuk mendekatkan pelayanan Dukcapil kepada masyarakat.', 'essay', 'hard', 5, 'Contoh: layanan jemput bola, layanan online/mandiri, aktivasi IKD, cetak dokumen mandiri ber-TTE, pelayanan di kelurahan/kecamatan, layanan khusus kelompok rentan.', 1);

INSERT INTO question_options (question_id, option_text, is_correct, sort_order) VALUES
(1, 'UU Nomor 23 Tahun 2006 sebagaimana diubah dengan UU Nomor 24 Tahun 2013', 1, 0),
(1, 'UU Nomor 12 Tahun 2006 tentang Kewarganegaraan', 0, 1),
(1, 'UU Nomor 25 Tahun 2009 tentang Pelayanan Publik', 0, 2),
(1, 'UU Nomor 1 Tahun 1974 tentang Perkawinan', 0, 3),
(2, '12 digit', 0, 0),
(2, '14 digit', 0, 1),
(2, '16 digit', 1, 2),
(2, '18 digit', 0, 3),
(3, 'Kode wilayah (provinsi, kabupaten/kota, kecamatan)', 1, 0),
(3, 'Tanggal, bulan, dan tahun lahir', 0, 1),
(3, 'Nomor urut penerbitan', 0, 2),
(3, 'Tahun pendaftaran penduduk', 0, 3),
(4, '20', 0, 0),
(4, '30', 0, 1),
(4, '40', 1, 2),
(4, '50', 0, 3),
(5, 'Benar', 1, 0),
(5, 'Salah', 0, 1),
(6, 'Telah berumur 17 tahun atau telah kawin / pernah kawin', 1, 0),
(6, 'Telah berumur 15 tahun', 0, 1),
(6, 'Telah berumur 21 tahun', 0, 2),
(6, 'Telah bekerja', 0, 3),
(7, 'Benar', 0, 0),
(7, 'Salah', 1, 1),
(8, 'Perpres Nomor 96 Tahun 2018', 1, 0),
(8, 'Perpres Nomor 95 Tahun 2018', 0, 1),
(8, 'Perpres Nomor 39 Tahun 2019', 0, 2),
(8, 'Perpres Nomor 81 Tahun 2010', 0, 3),
(9, 'Kelahiran', 1, 0),
(9, 'Kematian', 1, 1),
(9, 'Perkawinan', 1, 2),
(9, 'Pindah datang', 0, 3),
(10, 'Kartu Keluarga', 1, 0),
(10, 'KTP-el', 1, 1),
(10, 'Akta Kelahiran', 1, 2),
(10, 'Paspor', 0, 3),
(11, '14 hari', 0, 0),
(11, '30 hari', 0, 1),
(11, '60 hari', 1, 2),
(11, '90 hari', 0, 3),
(12, '7 hari', 0, 0),
(12, '14 hari', 0, 1),
(12, '30 hari', 1, 2),
(12, '60 hari', 0, 3),
(13, '14 hari', 0, 0),
(13, '30 hari', 0, 1),
(13, '60 hari', 1, 2),
(13, '1 tahun', 0, 3),
(14, 'KUA Kecamatan', 1, 0),
(14, 'Dinas Dukcapil', 0, 1),
(14, 'Pengadilan Negeri', 0, 2),
(14, 'Kantor Kelurahan', 0, 3),
(15, 'Benar', 1, 0),
(15, 'Salah', 0, 1),
(16, 'Akta Kematian', 1, 0),
(16, 'Kutipan Akta Kematian', 1, 1),
(17, 'Surat Keterangan Pindah', 1, 0),
(17, 'Surat Keterangan Domisili', 0, 1),
(17, 'Surat Pengantar RT/RW', 0, 2),
(17, 'Surat Keterangan Catatan Kepolisian', 0, 3),
(18, 'Anak berusia kurang dari 17 tahun dan belum kawin', 1, 0),
(18, 'Anak berusia kurang dari 5 tahun saja', 0, 1),
(18, 'Pelajar SMA', 0, 2),
(18, 'Anak berusia 17 tahun ke atas', 0, 3),
(19, 'Benar', 1, 0),
(19, 'Salah', 0, 1),
(20, 'Benar', 0, 0),
(20, 'Salah', 1, 1),
(21, 'Sistem Informasi Administrasi Kependudukan', 1, 0),
(22, 'Identitas Kependudukan Digital', 1, 0),
(22, 'Identitas Kartu Digital', 0, 1),
(22, 'Informasi Kependudukan Daerah', 0, 2),
(22, 'Identifikasi Kependudukan Data', 0, 3),
(23, 'Benar', 1, 0),
(23, 'Salah', 0, 1),
(24, 'Direktorat Jenderal Dukcapil Kementerian Dalam Negeri', 1, 0),
(24, 'Badan Pusat Statistik', 0, 1),
(24, 'Badan Kepegawaian Negara', 0, 2),
(24, 'Kementerian Hukum', 0, 3),
(25, 'Sidik jari', 1, 0),
(25, 'Iris mata', 1, 1),
(25, 'Tanda tangan', 1, 2),
(25, 'Nama kecamatan domisili', 0, 3),
(26, 'Pungutan liar (pungli)', 1, 0),
(26, 'Biaya administrasi resmi', 0, 1),
(26, 'Retribusi daerah', 0, 2),
(26, 'Bentuk pelayanan prima', 0, 3),
(27, 'UU Nomor 25 Tahun 2009', 1, 0),
(27, 'UU Nomor 23 Tahun 2014', 0, 1),
(27, 'UU Nomor 14 Tahun 2008', 0, 2),
(27, 'UU Nomor 30 Tahun 2014', 0, 3),
(28, 'Benar', 0, 0),
(28, 'Salah', 1, 1),
(29, 'Tetap tenang, mendengarkan keluhan, memberi penjelasan, dan menawarkan solusi', 1, 0),
(29, 'Meminta pemohon datang lagi besok tanpa penjelasan', 0, 1),
(29, 'Mendahulukan pemohon tersebut agar tidak marah', 0, 2),
(29, 'Membalas dengan nada tinggi agar pemohon diam', 0, 3);

INSERT INTO exams (id, title, description, instructions, type, duration, passing_grade, show_result, show_correct_answer,
                   random_question, random_answer, question_count, max_attempts, status, created_by) VALUES
(1, 'Pre-Test Pengetahuan Dasar Adminduk', 'Mengukur pemahaman awal aparatur tentang regulasi dan layanan Administrasi Kependudukan sebelum bimbingan teknis.',
 'Kerjakan seluruh soal dengan jujur dan mandiri.\nPre-Test ini untuk memetakan kemampuan awal Anda.\nScore dan pembahasan langsung tampil setelah submit.',
 'pretest', 30, 70, 1, 1, 0, 0, 0, 3, 'published', 1),
(2, 'Test Kompetensi Pelayanan Dukcapil', 'Ujian resmi kompetensi teknis pelayanan pendaftaran penduduk dan pencatatan sipil.',
 'Ini adalah TEST RESMI.\nSoal dan pilihan jawaban diacak untuk setiap peserta.\nDilarang membuka tab atau aplikasi lain selama ujian — aktivitas ini tercatat.\nHasil tidak ditampilkan setelah submit dan akan diproses oleh administrator.',
 'test', 60, 75, 0, 0, 1, 1, 20, 1, 'published', 1);

INSERT INTO exam_questions (exam_id, question_id, question_order) VALUES
(1, 1, 1),
(1, 2, 2),
(1, 3, 3),
(1, 4, 4),
(1, 5, 5),
(1, 6, 6),
(1, 7, 7),
(1, 8, 8),
(1, 9, 9),
(1, 10, 10),
(1, 11, 11),
(1, 12, 12),
(1, 13, 13),
(1, 14, 14),
(1, 15, 15),
(1, 16, 16),
(1, 17, 17),
(1, 18, 18),
(2, 1, 1),
(2, 2, 2),
(2, 3, 3),
(2, 4, 4),
(2, 5, 5),
(2, 6, 6),
(2, 7, 7),
(2, 8, 8),
(2, 9, 9),
(2, 10, 10),
(2, 11, 11),
(2, 12, 12),
(2, 13, 13),
(2, 14, 14),
(2, 15, 15),
(2, 16, 16),
(2, 17, 17),
(2, 18, 18),
(2, 19, 19),
(2, 20, 20),
(2, 21, 21),
(2, 22, 22),
(2, 23, 23),
(2, 24, 24),
(2, 25, 25),
(2, 26, 26),
(2, 27, 27),
(2, 28, 28),
(2, 29, 29),
(2, 30, 30),
(2, 31, 31);
